pipeline {
    agent any

    environment {
        IMAGE_NAME = "rahmouta/frontend-service"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'frontend-service-rahma',
                    url: 'https://github.com/Wiem2003/learnify-user-backend.git'
            }
        }

        stage('Verify Frontend') {
            steps {
                sh '''
                    ls -la frontend
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    cd frontend && docker build -t $IMAGE_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'Docker-ID',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    sh '''
                        echo $PASS | docker login -u $USER --password-stdin

                        docker push $IMAGE_NAME:$IMAGE_TAG

                        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
                        docker push $IMAGE_NAME:latest

                        docker logout
                    '''
                }
            }
        }
    }

    post {
        always {
            sh 'docker system prune -af || true'
        }
    }
}
