pipeline {
  agent any

  environment {
    MS_NAME = 'club-service'
    IMAGE_NAME = 'rahmouta/club-service'
    IMAGE_TAG = 'latest'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'final-club-service',
            url: 'https://github.com/Wiem2003/learnify-user-backend.git'
      }
    }

    stage('Build') {
      steps {
        dir("${MS_NAME}") {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Test') {
      steps {
        dir("${MS_NAME}") {
          sh 'mvn test'
        }
      }
      post {
        always {
          junit "${MS_NAME}/target/surefire-reports/*.xml"
        }
      }
    }

    stage('Build Docker') {
      steps {
        dir("${MS_NAME}") {
          sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
        }
      }
    }

    stage('Push Docker') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'Docker-ID',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
          '''
        }
      }
    }
  }

  post {
    always {
      sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
    }
  }
}
