pipeline {
  agent any

  environment {
    MS_NAME = 'club-service'
    IMAGE_NAME = 'rahmouta/club-service'
    IMAGE_TAG = "${env.BUILD_NUMBER}"
    JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
    PATH = "${JAVA_HOME}/bin:${env.PATH}"
    SONAR_HOST_URL = "http://localhost:9000"
    SONAR_PROJECT_KEY = "club-service"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'final-club-service',
            url: 'https://github.com/Wiem2003/learnify-user-backend.git'
      }
    }

    stage('Build') {
      steps {
        dir("${MS_NAME}") {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Test') {
      steps {
        dir("${MS_NAME}") {
          sh 'mvn test'
        }
      }
      post {
        always {
          junit "${MS_NAME}/target/surefire-reports/*.xml"
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        withCredentials([string(
          credentialsId: 'sonar-id',
          variable: 'SONAR_TOKEN'
        )]) {
          dir("${MS_NAME}") {
            sh '''
              mvn sonar:sonar \
                -Dsonar.projectKey=$SONAR_PROJECT_KEY \
                -Dsonar.host.url=$SONAR_HOST_URL \
                -Dsonar.login=$SONAR_TOKEN
            '''
          }
        }
      }
    }

    stage('Build Docker') {
      steps {
        dir("${MS_NAME}") {
          sh '''
            docker system prune -f
            docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          '''
        }
      }
    }

    stage('Push Docker') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'Docker-ID',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            docker logout || true
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/club-service/
        '''
      }
    }

    stage('Verify Deployment') {
      steps {
        sh '''
          kubectl get pods -A
          kubectl get svc -A
        '''
      }
    }
  }

  post {
    always {
      sh '''
        docker rmi $IMAGE_NAME:$IMAGE_TAG || true
        docker system prune -f || true
      '''
    }
  }
}
