
spring.datasource.url=jdbc:mysql://localhost:3306/learnify?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
sendgrid.api-key=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
sendgrid.from=wiempubg1972pw@gmail.com


webauthn.rpId=localhost
webauthn.rpName=learnify
webauthn.origin=http://localhost:4200

# ===== GOOGLE OAUTH2 =====
spring.security.oauth2.client.registration.google.client-id=347252530779-s7on04e1it4bu9todt6ph38fk8lcqp5j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# ===== api gateway =====
spring.application.name=USER-SERVICE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka