apiVersion: v1
kind: Secret
metadata:
  name: club-db-secret
  namespace: learnify
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "club_db"
  MYSQL_USER: "club_user"
  MYSQL_PASSWORD: "club_password"
  SPRING_MAIL_USERNAME: "rahmadraouil2020@gmail.com"
  SPRING_MAIL_PASSWORD: "whluzqxcwmnwtbwr"
