apiVersion: v1
kind: Secret
metadata:
  name: event-db-secret
  namespace: learnify
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "event_db"
  MYSQL_USER: "event_user"
  MYSQL_PASSWORD: "event_password"
